### ISSUE TITLE
README.md in the backend folder is missing

### ISSUE THREAD

**Issue by mortzel** [adacta-io/adacta#1]
The README.md in the backend folder is missing so there are no informations how to build the backend.

**Comment by fooker** [comment]
Fixed by https://github.com/adacta-io/adacta/commit/9bcf261abb3a05dbf8e120053d432e04f9b4355a. If further information is required, pleas feel free to ask.

**Comment by fooker** [comment]
Fixed by 9bcf261. If further information is required, pleas feel free to ask.
